source "http://rubygems.org"
source 'https://gems.gemfury.com/uDdMuaVsXVTd8HpbGwMc'

gem "rake"
gem "sinatra", "1.3.1"
gem "thin", "1.2.10"
gem "haml"
gem "pg"
gem "uuid"
gem "sequel"
gem "bcrypt-ruby"
gem "rack-flash"
gem "sinatra-redirect-with-flash"
gem "rest-client"
gem "resque"
gem "rfc822"
gem "newrelic_rpm"
gem "vellup-data", "0.0.1"